# Generated by Django 5.1.6 on 2025-03-10 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACH',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('approved', 'approved'), ('processing', 'processing'), ('initiated', 'initiated'), ('failed', 'failed'), ('refunded', 'refunded')], default='initiated', max_length=255)),
                ('bank_name', models.CharField(max_length=100)),
                ('acc_number_last_four', models.CharField(max_length=4)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ach_payment', to='bookings.airlinereservation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('approved', 'approved'), ('processing', 'processing'), ('initiated', 'initiated'), ('failed', 'failed'), ('refunded', 'refunded')], default='initiated', max_length=255)),
                ('cash_tendered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_payment', to='bookings.airlinereservation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('approved', 'approved'), ('processing', 'processing'), ('initiated', 'initiated'), ('failed', 'failed'), ('refunded', 'refunded')], default='initiated', max_length=255)),
                ('name_on_card', models.CharField(max_length=100)),
                ('last_four_digits', models.PositiveIntegerField()),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creditcard_payment', to='bookings.airlinereservation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
