# Generated by Django 5.1.6 on 2025-03-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
