# Generated by Django 5.1.6 on 2025-03-10 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flightseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='flights.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='flights.airport'),
        ),
    ]
