# Generated by Django 5.1.6 on 2025-04-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_pilot_pilotid'),
        ('flights', '0003_alter_flight_aircraft_alter_flight_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='crew_members',
            field=models.ManyToManyField(blank=True, related_name='crew_flights', to='authentication.crew'),
        ),
        migrations.AddField(
            model_name='flight',
            name='pilots',
            field=models.ManyToManyField(blank=True, related_name='assigned_flights', to='authentication.pilot'),
        ),
    ]
