# Generated by Django 5.1.6 on 2025-03-10 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_customer_frequentflyingnumber'),
        ('flights', '0002_flightseat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='authentication.customer')),
                ('final_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_itineraries', to='flights.airport')),
                ('starting_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_itineraries', to='flights.airport')),
            ],
        ),
    ]
