# Generated by Django 5.1.6 on 2025-03-10 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('flights', '0003_alter_flight_arrival_alter_flight_departure'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationNumber', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Cancelled by customer', 'Cancelled by customer'), ('Cancelled by airline', 'Cancelled by airline'), ('Pending', 'Pending')], default='Pending', max_length=30)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='flights.flight')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bookings.itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bookings.airlinereservation')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightseat')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.passenger')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.airlinereservation')),
            ],
        ),
        migrations.AddField(
            model_name='airlinereservation',
            name='seat_map',
            field=models.ManyToManyField(through='bookings.PassengerSeat', to='flights.flightseat'),
        ),
    ]
