# Generated by Django 5.1.6 on 2025-03-10 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('bookings', '0001_initial'),
        ('flights', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlinereservation',
            name='payment_ach',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_ach', to='payments.ach'),
        ),
        migrations.AddField(
            model_name='airlinereservation',
            name='payment_cash',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_cash', to='payments.cash'),
        ),
        migrations.AddField(
            model_name='airlinereservation',
            name='payment_credit_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_credit_card', to='payments.creditcard'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='authentication.customer'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='final_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_itineraries', to='flights.airport'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='starting_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_itineraries', to='flights.airport'),
        ),
        migrations.AddField(
            model_name='airlinereservation',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bookings.itinerary'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bookings.airlinereservation'),
        ),
        migrations.AddField(
            model_name='passengerseat',
            name='flight_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightseat'),
        ),
        migrations.AddField(
            model_name='passengerseat',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.passenger'),
        ),
        migrations.AddField(
            model_name='passengerseat',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.airlinereservation'),
        ),
        migrations.AddField(
            model_name='airlinereservation',
            name='seat_map',
            field=models.ManyToManyField(through='bookings.PassengerSeat', to='flights.flightseat'),
        ),
    ]
