# Generated by Django 5.1.6 on 2025-04-04 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('flights', '0004_flight_crew_members_flight_pilots'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerseat',
            name='baggage_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passengerseat',
            name='extra_baggage_allowed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='passengerseat',
            name='travel_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FlightBaggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capacity_kg', models.FloatField()),
                ('used_capacity_kg', models.FloatField(default=0)),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
            ],
        ),
    ]
