# Generated by Django 5.1.6 on 2025-04-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_passengerseat_baggage_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerseat',
            name='baggage_weight',
        ),
        migrations.RemoveField(
            model_name='passengerseat',
            name='extra_baggage_allowed',
        ),
        migrations.RemoveField(
            model_name='passengerseat',
            name='travel_count',
        ),
        migrations.AddField(
            model_name='passenger',
            name='baggage_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='extra_baggage_allowed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='passenger',
            name='travel_count',
            field=models.IntegerField(default=0),
        ),
    ]
