# Generated by Django 5.1.6 on 2025-04-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_passengerseat_baggage_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='extra_baggage_allowed',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='travel_count',
        ),
    ]
