# Generated by Django 5.1.6 on 2025-03-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='frequentFlyingNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
