# Generated by Django 5.1.6 on 2025-04-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_pilot_pilotid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='extra_baggage_allowed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='travel_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
